name: mcpack
on:
  push:
    branches:
      - main
    tags:
      - v1.*
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create archive
        env:
          RP_DIR: ./RP
          PACK_NAME: ${{ github.ref }}
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          tar -a -c -f ${{ env.PACK_NAME }}.mcpack $RP_DIR
